apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chatbot-backend-hpa
  labels:
    app: chatbot-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatbot-backend-deployment
  minReplicas: {{ .Values.backend.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.backend.hpa.targetCPU }}
